# Generated by Django 4.1.2 on 2022-10-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(null=True, upload_to='books'),
        ),
    ]
