# Generated by Django 4.1.2 on 2022-10-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0004_remove_menuitem_description_remove_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(null=True, upload_to='menuitems'),
        ),
    ]
